# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SCB\Documents\eclipseWS\MachineControlGui\layout\mainui.ui'
#
# Created: Tue Sep 17 12:43:32 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 575)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.thumperImage = QtGui.QLabel(self.centralwidget)
        self.thumperImage.setGeometry(QtCore.QRect(50, 40, 221, 351))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumperImage.sizePolicy().hasHeightForWidth())
        self.thumperImage.setSizePolicy(sizePolicy)
        self.thumperImage.setFrameShape(QtGui.QFrame.Box)
        self.thumperImage.setText(_fromUtf8(""))
        self.thumperImage.setObjectName(_fromUtf8("thumperImage"))
        self.obstacleLeftTop = QtGui.QProgressBar(self.centralwidget)
        self.obstacleLeftTop.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.obstacleLeftTop.setProperty("value", 24)
        self.obstacleLeftTop.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.obstacleLeftTop.setTextVisible(True)
        self.obstacleLeftTop.setOrientation(QtCore.Qt.Horizontal)
        self.obstacleLeftTop.setInvertedAppearance(True)
        self.obstacleLeftTop.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.obstacleLeftTop.setObjectName(_fromUtf8("obstacleLeftTop"))
        self.obstacleRightTop = QtGui.QProgressBar(self.centralwidget)
        self.obstacleRightTop.setGeometry(QtCore.QRect(220, 20, 101, 21))
        self.obstacleRightTop.setProperty("value", 24)
        self.obstacleRightTop.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.obstacleRightTop.setTextVisible(True)
        self.obstacleRightTop.setOrientation(QtCore.Qt.Horizontal)
        self.obstacleRightTop.setInvertedAppearance(True)
        self.obstacleRightTop.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.obstacleRightTop.setObjectName(_fromUtf8("obstacleRightTop"))
        self.camDirection = QtGui.QLabel(self.centralwidget)
        self.camDirection.setGeometry(QtCore.QRect(130, 100, 61, 61))
        self.camDirection.setFrameShape(QtGui.QFrame.Box)
        self.camDirection.setText(_fromUtf8(""))
        self.camDirection.setObjectName(_fromUtf8("camDirection"))
        self.obstacleBottom = QtGui.QProgressBar(self.centralwidget)
        self.obstacleBottom.setGeometry(QtCore.QRect(110, 390, 101, 21))
        self.obstacleBottom.setProperty("value", 24)
        self.obstacleBottom.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.obstacleBottom.setTextVisible(True)
        self.obstacleBottom.setOrientation(QtCore.Qt.Horizontal)
        self.obstacleBottom.setInvertedAppearance(True)
        self.obstacleBottom.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.obstacleBottom.setObjectName(_fromUtf8("obstacleBottom"))
        self.obstacleTop = QtGui.QProgressBar(self.centralwidget)
        self.obstacleTop.setGeometry(QtCore.QRect(120, 20, 101, 21))
        self.obstacleTop.setMinimum(0)
        self.obstacleTop.setMaximum(100)
        self.obstacleTop.setProperty("value", 11)
        self.obstacleTop.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.obstacleTop.setTextVisible(True)
        self.obstacleTop.setOrientation(QtCore.Qt.Horizontal)
        self.obstacleTop.setInvertedAppearance(True)
        self.obstacleTop.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.obstacleTop.setObjectName(_fromUtf8("obstacleTop"))
        self.rotationViewer = QtGui.QLabel(self.centralwidget)
        self.rotationViewer.setGeometry(QtCore.QRect(320, 190, 41, 201))
        self.rotationViewer.setFrameShape(QtGui.QFrame.Box)
        self.rotationViewer.setText(_fromUtf8(""))
        self.rotationViewer.setObjectName(_fromUtf8("rotationViewer"))
        self.wlabel = QtGui.QLabel(self.centralwidget)
        self.wlabel.setGeometry(QtCore.QRect(600, 40, 61, 16))
        self.wlabel.setObjectName(_fromUtf8("wlabel"))
        self.camViewer = QtGui.QLabel(self.centralwidget)
        self.camViewer.setGeometry(QtCore.QRect(510, 60, 151, 91))
        self.camViewer.setFrameShape(QtGui.QFrame.Box)
        self.camViewer.setText(_fromUtf8(""))
        self.camViewer.setObjectName(_fromUtf8("camViewer"))
        self.wlabel_2 = QtGui.QLabel(self.centralwidget)
        self.wlabel_2.setGeometry(QtCore.QRect(600, 170, 61, 20))
        self.wlabel_2.setObjectName(_fromUtf8("wlabel_2"))
        self.wlabel_3 = QtGui.QLabel(self.centralwidget)
        self.wlabel_3.setGeometry(QtCore.QRect(300, 60, 181, 91))
        self.wlabel_3.setFrameShape(QtGui.QFrame.Box)
        self.wlabel_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.wlabel_3.setLineWidth(1)
        self.wlabel_3.setMidLineWidth(0)
        self.wlabel_3.setText(_fromUtf8(""))
        self.wlabel_3.setObjectName(_fromUtf8("wlabel_3"))
        self.logPanel = QtGui.QPlainTextEdit(self.centralwidget)
        self.logPanel.setEnabled(False)
        self.logPanel.setGeometry(QtCore.QRect(30, 440, 631, 91))
        self.logPanel.setUndoRedoEnabled(False)
        self.logPanel.setReadOnly(False)
        self.logPanel.setObjectName(_fromUtf8("logPanel"))
        self.connectStateIndicator = QtGui.QLabel(self.centralwidget)
        self.connectStateIndicator.setGeometry(QtCore.QRect(320, 100, 31, 31))
        self.connectStateIndicator.setText(_fromUtf8(""))
        self.connectStateIndicator.setObjectName(_fromUtf8("connectStateIndicator"))
        self.wlabel_4 = QtGui.QLabel(self.centralwidget)
        self.wlabel_4.setGeometry(QtCore.QRect(310, 70, 51, 16))
        self.wlabel_4.setObjectName(_fromUtf8("wlabel_4"))
        self.leftBatteryState = QtGui.QProgressBar(self.centralwidget)
        self.leftBatteryState.setGeometry(QtCore.QRect(370, 80, 101, 21))
        self.leftBatteryState.setMinimum(6400)
        self.leftBatteryState.setMaximum(8400)
        self.leftBatteryState.setProperty("value", 6911)
        self.leftBatteryState.setAlignment(QtCore.Qt.AlignCenter)
        self.leftBatteryState.setTextVisible(True)
        self.leftBatteryState.setOrientation(QtCore.Qt.Horizontal)
        self.leftBatteryState.setObjectName(_fromUtf8("leftBatteryState"))
        self.rightBatteryState = QtGui.QProgressBar(self.centralwidget)
        self.rightBatteryState.setGeometry(QtCore.QRect(370, 112, 101, 21))
        self.rightBatteryState.setMinimum(6400)
        self.rightBatteryState.setMaximum(8400)
        self.rightBatteryState.setProperty("value", 6399)
        self.rightBatteryState.setAlignment(QtCore.Qt.AlignCenter)
        self.rightBatteryState.setObjectName(_fromUtf8("rightBatteryState"))
        self.mapView = QtWebKit.QWebView(self.centralwidget)
        self.mapView.setGeometry(QtCore.QRect(380, 190, 281, 201))
        self.mapView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.mapView.setObjectName(_fromUtf8("mapView"))
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.centralwidget)
        self.videoPlayer.setGeometry(QtCore.QRect(510, 60, 151, 91))
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuStatus = QtGui.QMenu(self.menubar)
        self.menuStatus.setObjectName(_fromUtf8("menuStatus"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionSaveLog = QtGui.QAction(MainWindow)
        self.actionSaveLog.setObjectName(_fromUtf8("actionSaveLog"))
        self.actionBattery = QtGui.QAction(MainWindow)
        self.actionBattery.setObjectName(_fromUtf8("actionBattery"))
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionSaveLog)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuStatus.addAction(self.actionBattery)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStatus.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.obstacleLeftTop.setFormat(_translate("MainWindow", "%p", None))
        self.obstacleRightTop.setFormat(_translate("MainWindow", "%p", None))
        self.obstacleBottom.setFormat(_translate("MainWindow", "%p", None))
        self.obstacleTop.setFormat(_translate("MainWindow", "%p", None))
        self.wlabel.setText(_translate("MainWindow", "Cam View", None))
        self.wlabel_2.setText(_translate("MainWindow", "Map View", None))
        self.wlabel_4.setText(_translate("MainWindow", "STATUS", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuStatus.setTitle(_translate("MainWindow", "Status", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect", "Cddd"))
        self.actionSaveLog.setText(_translate("MainWindow", "Save log", None))
        self.actionBattery.setText(_translate("MainWindow", "Battery", None))

from PyQt4 import phonon
from PyQt4 import QtWebKit
